name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    paths-ignore:
    - README.md
    - notes/**.md

    steps:
    - uses: actions/checkout@master
    - uses: danielweller-swp/postgresql-action@v2
      with:
        postgresql version: '11'
        postgresql init scripts: 'sql/postgresql'
        postgresql user: 'postgres'
        postgresql password: 'password' 
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt  
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v1
